version = 1

[[annotations]]
path = ["**.rs"]
SPDX-FileCopyrightText = "fluent-i18n contributors"
SPDX-License-Identifier = "Apache-2.0 OR MIT"

[[annotations]]
path = [
  "**.ftl",
  "**.toml",
  "**.lock",
  ".git*"
]
SPDX-FileCopyrightText = "fluent-i18n contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**.md"]
SPDX-FileCopyrightText = "fluent-i18n contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"
