version = 1

[[annotations]]
SPDX-FileCopyrightText = "fluent-i18n contributors"
SPDX-License-Identifier = "Apache-2.0 OR MIT"
path = ["**.rs"]

[[annotations]]
SPDX-FileCopyrightText = "fluent-i18n contributors"
SPDX-License-Identifier = "CC0-1.0"
path = ["**.ftl", "**.lock", "**.toml", ".git*"]

[[annotations]]
SPDX-FileCopyrightText = "fluent-i18n contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"
path = ["**.md"]
